import BirdDoll from './BirdDoll.jpg';
import Cartera from './Cartera.jpg';
import Cartera2 from './Cartera2.jpg';
import Colgante from './Colgante.jpg';
import Colgante2 from './Colgante2.jpg';
import Colgante3 from './Colgante3.jpg';
import Colgante4 from './Colgante4.jpg';
import Colgante5 from './Colgante5.jpg';
import Colgante6 from './Colgante6.jpg';
import Colgante7 from './Colgante7.jpg';
import Doll from './Doll.jpg';
import Doll2 from './Doll2.jpg';
import Dolls from './Dolls.jpg';
import Flor from './Flor.jpg';
import Flor2 from './Flor2.jpg';
import Flores from './Flores.jpg';
import Flores2 from './Flores2.jpg';
import GirlDoll from './GirlDoll.jpg';
import GirlDoll2 from './GirlDoll2.jpg';
import MiniDoll from './MiniDoll.jpg';
import MiniDoll2 from './MiniDoll2.jpg';
import MiniDoll3 from './MiniDoll3.jpg';
import OwlDoll from './OwlDoll.jpg';
import OwlDoll2 from './OwlDoll2.jpg';
import OwlDoll3 from './OwlDoll3.jpg';
import Rosario from './Rosario.jpg';
import Rosarios from './Rosarios.jpg';
import Vasija from './Vasija.jpg';
import Vasija2 from './Vasija2.jpg';
import Vasija3 from './Vasija3.jpg';

export { BirdDoll }
export { Cartera }
export { Cartera2 }
export { Colgante }
export { Colgante2 }
export { Colgante3 }
export { Colgante4 }
export { Colgante5 }
export { Colgante6 }
export { Colgante7 }
export { Doll }
export { Doll2 }
export { Dolls }
export { Flor }
export { Flor2 }
export { Flores }
export { Flores2 }
export { GirlDoll }
export { GirlDoll2 }
export { MiniDoll }
export { MiniDoll2 }
export { MiniDoll3 }
export { OwlDoll }
export { OwlDoll2 }
export { OwlDoll3 }
export { Rosario }
export { Rosarios }
export { Vasija }
export { Vasija2 }
export { Vasija3 }